- name: Install chromium
  become: yes
  package:
    name: chromium
    state: present

      
- name: Create chromium extensions directory
  become: yes
  file:
    path: /usr/share/chromium-browser/extensions
    state: directory

- name: Create chromium JSON files to install extensions 
  become: yes
  template:
    src: extension.json
    dest: "/usr/share/chromium-browser/extensions/{{ item }}.json"
  with_items:
    - cimiefiiaegbelhefglklhhakcgmhkai
    - dbepggeogbaibhgnhhndojpepiihcmeb
    - onhiacboedfinnofagfgoaanfedhmfab
