- name: Installs tmux
  become: yes
  package:
    name: tmux
    state: present

- name: Links .tmux.conf
  file:
    src: {{ lookup('env', 'DOTFILES') }}/roles/tmux/files/tmux.conf
    dest: {{ lookup('env', 'HOME') }}/.tmux.conf
