#!/usr/bin/bash

DOTFILES="$HOME/.dotfiles"
HOSTS="$DOTFILES/hosts"
PLAYBOOK="$DOTFILES/main.yml"

export DOTFILES

if ! [ -x "$(command -v ansible)" ]; then
  sudo pacman -S ansible --noconfirm
fi

TAGS=$(printf ", %s" "$@")

if [[ -z $1 ]]; then
    ansible-playbook -i $HOSTS $PLAYBOOK --ask-become-pass 
else
    ansible-playbook -i $HOSTS $PLAYBOOK --ask-become-pass --tags "$TAGS" 
fi

