- name: Install kitty
  become: yes
  package:
    name: kitty
    state: present

- name: Link config
  file:
    src: "{{ lookup('env', 'DOTFILES') }}/roles/kitty/files"
    dest: "{{ lookup('env', 'HOME') }}/.config/kitty"
    state: link
    force: yes
