- name: Install tmux
  become: yes
  package:
    name: tmux
    state: present

- name: Install tmux-plugin-manager
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
    depth: 1

- name: Link .tmux.conf
  file:
    src: "{{ lookup('env', 'DOTFILES') }}/roles/tmux/files/tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
    state: link
    force: yes

- name: Link tmuxinator projects
  file:
    src: "{{ lookup('env', 'DOTFILES') }}/roles/tmux/files/templates"
    dest: "{{ lookup('env', 'HOME') }}/.tmuxinator"
    state: link
    force: yes
