#!/bin/sh

zsh_config_path="$HOME/.config/zsh"
zsh_aliases_path="$zsh_config_path/aliases-generated"
lf_go_mappings_path="$HOME/.config/lf/go-mappings"

echo "" > $zsh_aliases_path

sed '/^#.*/d; /^$/d' $DOTFILES/folders | \
    awk '{ printf "alias d%s=\"cd %s\"\n", $1, $2 }' >> $zsh_aliases_path

sed '/^#.*/d; /^$/d' $DOTFILES/folders | \
    awk '{ printf "alias v%s=\"nvim %s\"\n", $1, $2 }' >> $zsh_aliases_path

sed '/^#.*/d; /^$/d' $DOTFILES/folders | \
    awk '{ printf "map g%s cd %s\n", $1, $2 }' > $lf_go_mappings_path
