#!/usr/bin/bash

ZOXIDE_RESULT=$(zoxide query -l | fzf --reverse)

if [ -z $ZOXIDE_RESULT ]; then
    exit 0
fi

FOLDER=$(basename $ZOXIDE_RESULT)
SESSION=$(tmux list-sessions | grep $FOLDER | awk '{print $1}')
SESSION=${SESSION//:/}
cd $ZOXIDE_RESULT

# if outside of tmux
if [ -z $TMUX ]; then

    # if session does not exists
    if [ -z $SESSION ]; then
        tmux new-session -s $FOLDER
    else 
        tmux attach -t $SESSION
    fi
# else inside of tmux
else

    # if session does not exists
    if [ -z $SESSION ]; then
        tmux new-session -d -s $FOLDER
    fi 

    tmux switch-client -t $SESSION
fi
