#!/usr/bin/bash

FOLDER=$(pwd)
FOLDER=$(basename $FOLDER)

SESSION=$(tmux list-sessions | grep $FOLDER | awk '{print $1}')
SESSION=${SESSION//:/}

zoxide add $FOLDER

# if session does not exists
if [ -z $SESSION ]; then
    tmux new-session -d -s $FOLDER
fi 

# if outside of tmux
if [ -z $TMUX ]; then
    tmux attach -t $SESSION
# else inside of tmux
else
    tmux switch-client -t $SESSION
fi

