#!/bin/sh

kill_session_keybinding="alt-k"

projects() {
    tmuxp ls | fzf | xargs tmuxp load -y
}

switch_client() {
    if [ -z $TMUX ]; then
        tmux attach -t $1
    else
        tmux switch-client -t $1
    fi
}

sessions() {
    switch_client $(tmux ls -F "#{session_name}" | fzf \
        --bind "$kill_session_keybinding:execute(tmux kill-session -t {})+reload(tmux ls -F \"#{session_name}\")")
}

new() {
    tmux new-session -t "$(basename "`pwd`")"
}

case "$1" in
    projects)
        projects ;;
    sessions)
        sessions ;;
    new)
        new ;;
    *)
        tmux attach
esac

