#!/usr/bin/bash

SESSIONS=$(tmux ls -F "#{session_name}")
SESSIONS="${SESSIONS// /$'\n'}"
SESSION=$(echo "$SESSIONS" | fzf)

if [ -z $SESSION ]; then
    exit 0
fi

# if outside of tmux
if [ -z $TMUX ]; then
    tmux attach -t $SESSION
# else inside of tmux
else
    tmux switch-client -t $SESSION
fi
