#!/bin/sh

file=~/dox/notes/tasks/watch-later.md

clipboard=$(xclip -o)
comment=$(echo "" | rofi -dmenu -p "Comment")

if [ -n comment ]; then
    result="- $comment - $clipboard"
else
    result="- $clipboard"
fi

echo $result >> $file

