- name: Install soft
  become: yes
  package:
    name:
      - curl
      - fzf
      - zoxide
      - nitrogen
      - composer
      - entr
      - lua
      - pip
    state: present

- name: Install howdoi
  become: yes
  shell:
    pip install howdoi
